# Generated by Django 5.0.2 on 2024-03-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('detail', models.TextField(verbose_name='내용')),
                ('pos_x', models.FloatField()),
                ('pos_y', models.FloatField()),
            ],
        ),
    ]
