# Generated by Django 5.0.2 on 2024-03-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('member_id', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'crews',
            },
        ),
    ]
